<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\task18\task18.csproj" />
      <ProjectReference Include="..\task19\task19.csproj" />
      <ProjectReference Include="..\task21\task21.csproj" />
      <PackageReference Include="ScottPlot" Version="5.0.47" />
    </ItemGroup>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

</Project>
